[global]
# info = [ {tag="mameversion", value="0229"} ]
mraauthor=["jotego"]

[features]
# qsound=true
# debug=true

[parse]
sourcefile=[ "sbasketb.cpp" ]
skip.setnames=["sbasketh", "hypersptb"]

[buttons]
names=[
    { names="Bounce,Throw,Pass" }
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]
# base = 16

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu" },
    { name="audiocpu" },
    { name="tiles" }, # start=$GFX1_START
    { name="sprites" }, # start=$GFX2_START
    { name="vlm" },
    { name="proms"          },
]

order = [
    "maincpu", "audiocpu", "tiles", "sprites", "vlm", "proms"
]


