[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "dec0.cpp" ]
skip.bootlegs=true
mustbe.machines=[ "secretag", "bouldash" ]

[buttons]
Names = [
    { names="Shot,Jump"},
]

[dipsw]
bitcnt = 16
base = 17
delete=[{names=["Unused","Unknown"]}]
rename = [
    { name="Enemy Power Decrease on Continue", to="Player strength"},
    { name="Control Panel Type", to="Panel" },
    { name="Player & Enemy Energy", to="Energy scale"},
    { name="L/R control related (keep off)", to="Unknown" }
]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true },
    { name="audiocpu", start="SND_START", no_offset=true  },
    { name="oki",      start="PCM_START" },

    # GFX1
    { name="gfx1",     start="BA2_START", width=16, no_offset=true },

    # GFX2
    { name="gfx2",     start="GFX2_START",width=16, no_offset=true,  ext_sort=[
    "14d","14f","12d","12f","17d","17f","15d","15f","9h","9f","8h","8f"], sort_even=true },

    # GFX3
    { name="gfx3",     start="GFX3_START", width=16, no_offset=true },

    { name="gfx4",     start="BA3_START", width=32, no_offset=true, sort_even=true },
    { name="sub",      start="MCU_START" },
    { name="mcu",      start="MCU_START" },
    { name="proms",    start="JTFRAME_PROM_START" },
    { name="plds",     skip=true         }
]

order = [
    "maincpu", "audiocpu", "oki",
    "gfx1", "gfx2", "gfx3", "gfx4", "mcu", "sub", "proms"
]

splits = [
    { machine="secretag", region="gfx1", offset=0x10000 },
    # { machine="birdtry",  region="gfx1", offset=0x4000, min_len=0x10000 }
]

