[global]
mraauthor=["jotego"]

[parse]
sourcefile=[ "gng.cpp" ]
skip.Setnames=["diamond"]

[buttons]
core=2 # max number of buttons supported by the core
names=[
    { names="Fire,Jump" }
]

[dipsw]
Rename = [
    { name="Bonus Life", to="Bonus" },
    { name="Invulnerability (Cheat)", to="Cheat" },
]

[ROM]
regions=[
    { name="maincpu", sequence=[1,0,2], no_offset=true },
    { setname="gngprot", name="maincpu", sequence=[1,2,0,3,4], no_offset=true },
    { setname="gnga", name="maincpu", sequence=[1,2,0,3,4], no_offset=true },
    { name="tiles", sequence=[2,3,4,5,0,1,0,1], no_offset=true },
    { name="sprites", sequence=[0,1,2,2,3,4,5,5], no_offset=true },
    { name="proms", skip=true },
    { name="plds", skip=true }
]

order = [ "maincpu", "chars", "audiocpu", "tiles", "sprites" ]