name: Compile all MiSTer cores

on:
  workflow_dispatch:
  repository_dispatch:
    types: rebuild
  schedule:
    - cron: '0 0 * * mon' # runs every Monday
jobs:
  list_cores:
    runs-on: ubuntu-latest
    outputs:
      cores: ${{ steps.generate-matrix.outputs.cores }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{secrets.PAT}} # Personal Access Token, must be defined in the repo's secrets
    - id: generate-matrix
      run: |
        cd cores
        # Get list of cores ready for compilation
        CORES='['
        for i in *; do
          if [[ -e $i/cfg/macros.def && ! -e $i/cfg/skip ]]; then
            if [ "$CORES" != '[' ]; then CORES="$CORES, "; fi
            CORES="$CORES \"$i\""
          fi
        done
        CORES="$CORES ]"
        echo $CORES
        echo "cores=${CORES}" >> $GITHUB_OUTPUT

  compile_cores17:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs:
      - list_cores
    strategy:
      fail-fast: false
      matrix:
        core: ${{ fromJSON(needs.list_cores.outputs.cores) }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.PAT }}
      - id: compile
        run: |
          # Compilation on Quartus 17
          docker run --network host -v `pwd`:/jtcores jotego/jtcore17x xjtcore.sh ${{matrix.core}}
      - id: upload
        uses: actions/upload-artifact@v3
        with:
          name: jtcore17_rbf
          path: release
